name = Configd
version = 0.001
author = George S. Baugh <george@troglodyne.net>
license = MIT
copyright_holder = Troglodyne LLC
copyright_year = 2026

; Simpler than doing include_dotfiles, and due to other dzil brain damage
[Run::BeforeBuild]
run = rm -rf .build/*
[Run::Test]
run = cp $(git rev-parse --show-toplevel)/.perltidyrc            .perltidyrc
run = cp $(git rev-parse --show-toplevel)/.perlcriticrc          .perlcriticrc
run = cp $(git rev-parse --show-toplevel)/.preferred_modules.ini .preferred_modules.ini
run = cp $(git rev-parse --show-toplevel)/LICENSE                LICENSE
run = echo .perltidyrc >> MANIFEST
run = echo .perlcriticrc >> MANIFEST
run = echo .preferred_modules.ini >> MANIFEST
[GatherDir]
exclude_filename = LICENSE
exclude_match    = cover_db/.+
[MetaYAML]
[MetaJSON]
[License]
[Readme]
[InstallGuide]
[ExtraTests]
[ExecDir]
[MakeMaker]
[Manifest]
[PruneCruft]
[ManifestSkip]

[AutoPrereqs]
[PkgVersion]
[PodWeaver]

[@TestingMania]
critic_config = .perlcriticrc
disable = Test::Portability
disable = Test::CPAN::Changes

[MetaNoIndex]
    directory = t
    directory = docs

[GithubMeta]
issues = 1
user = teodesian
